name: pkasolver_env
channels:
  - conda-forge
  - defaults
  - mro
dependencies:
  - rdkit==2022.9
  - jupyter
  - pandas
 pip:
      - torch==1.13.1+cpu
      - torch-scatter
      - torch-sparse
      - torch-spline-conv
      - cairosvg
      - svgutils
      - molvs

